// Command inspector-poc exercises the inspector / form architecture
// end-to-end: build a small live tree by hand, register form factories
// with a Designer, and generate Builder-mode source for that tree to
// stdout. The output is a fragment that can be pasted after a
// "NewBuilder(theme)" call.
package main

import (
	"fmt"
	"os"

	"github.com/tekugo/zeichenwerk/core"
	"github.com/tekugo/zeichenwerk/designer"
	"github.com/tekugo/zeichenwerk/widgets"
)

func main() {
	// Build the live tree by hand:
	//
	//   VFlex root
	//     ├── HFlex (header row)
	//     │     ├── Static "title"
	//     │     └── Input "search" (with placeholder)
	//     └── Grid 2x2
	//           ├── Static "Hello" at (0,0)
	//           └── Static "World" at (1,0) with class="highlight"
	root := widgets.NewFlex("root", "", core.Stretch, 1)
	root.SetFlag(core.FlagVertical, true)

	header := widgets.NewFlex("header", "", core.Center, 2)
	title := widgets.NewStatic("title", "", "Inspector PoC")
	search := widgets.NewInput("search", "", "", "type to filter…")
	_ = header.Add(title)
	_ = header.Add(search)
	_ = root.Add(header)

	grid := widgets.NewGrid("g1", "", 2, 2, false)
	s1 := widgets.NewStatic("s1", "", "Hello")
	grid.Add(s1, 0, 0, 1, 1)
	s2 := widgets.NewStatic("s2", "highlight", "World")
	grid.Add(s2, 1, 0, 1, 1)
	_ = root.Add(grid)

	// Register form factories.
	d := designer.NewDesigner(root)
	designer.RegisterDefaults(d)

	// Generate Builder-mode source as a chained expression
	// fragment. GenerateFile is the alternative when a complete,
	// directly-runnable file is needed.
	fmt.Println("// generated by inspector-poc")
	if err := d.GenerateFragment(designer.ModeBuilder, os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}
